name: Multiarch build for bundle-index

on:
  push:
    branches:
        master
    tags:
      - v**
    
env:
  IMAGE_NAME: compliance-operator-index
  IMAGE_TAG: multi-arch
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: aditijadhav

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - name: add checkout action...
        uses: actions/checkout@v2
      - name: test print
        run: echo "Hello World"
      - name: Fetch latest release version
        uses: reloc8/action-latest-release-version@1.0.0
        id: fetch-latest-release
      - name: Set Env Tags
        run: echo RELEASE_TAG=${{ steps.fetch-latest-release.outputs.latest-release }} >> $GITHUB_ENV

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
            
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
