name: Multiarch build for bundle

on:
  push:
    branches:
        master
    tags:
      - v**
env:
  IMAGE_NAME: compliance-operator-bundle
  IMAGE_TAG: multi-arch
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: aditijadhav

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - name: add checkout action...
        uses: actions/checkout@v2
      - name: test print
        run: echo "Hello World"
      - name: Fetch latest release version
        uses: reloc8/action-latest-release-version@1.0.0
        id: fetch-latest-release
      - name: Set Env Tags
        run: echo RELEASE_TAG=${{ steps.fetch-latest-release.outputs.latest-release }} >> $GITHUB_ENV

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
            
      - name: Build image linux/amd64
        run: |
            echo "Inside run"
            sudo apt-get install -y make
            echo "Installed make"
            sudo make index-image
             
                   
      
