kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  privileged: true
  
- name: Login to Quay.io
  uses: azure/docker-login@v1
  with:
    login-server: quay.io
    username: ${{ secrets.QUAY_USERNAME }}
    password: ${{ secrets.QUAY_PASSWORD }}  
  
  environment:
    GOOS: linux
    GOARCH: ppc64le
    DOCKER_CLI_EXPERIMENTAL: enabled
  
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock

  commands:
  - docker buildx version
  - docker buildx create --driver docker-container --use
  - docker buildx build --platform linux/amd64,linux/ppc64le -t openscap-ocp -f images/openscap/Dockerfile .
  - docker images
 
  
  
  
volumes:
- name: docker socket
  host:
    path: /var/run/docker.sock
